from __future__ import annotations

import base64
import codecs
import re
import urllib.parse
from dataclasses import dataclass, field
from typing import List


@dataclass
class DecodedVariant:
    """Represents a specific decoded output variant from the PayloadDecoder."""
    strategy: str
    decoded_text: str


@dataclass
class DeobfuscationReport:
    """Report generated by PayloadDecoder containing all evaluated variants."""
    original_text: str
    decoded_variants: List[DecodedVariant] = field(default_factory=list)
    contains_hidden_tokens: bool = False


class PayloadDecoder:
    """
    De-Obfuscation & Multi-Decoder Module.
    Extracts and normalizes text that may be obfuscated using Base64, Hex, URL encoding,
    ROT13, or character de-spacing techniques.
    """

    @staticmethod
    def _is_mostly_readable_utf8(text: str) -> bool:
        """
        Simple heuristic to check if a decoded string is mostly readable ASCII/UTF-8
        rather than random binary noise.
        """
        if not text:
            return False
        # Count printable characters
        printable = sum(1 for c in text if c.isprintable() or c in ('\n', '\r', '\t'))
        # If >80% printable, consider it readable text
        return printable / len(text) > 0.8

    @classmethod
    def decode_base64(cls, text: str) -> List[str]:
        """Extracts and decodes valid Base64 blocks of length >= 16."""
        # Find potential base64 blocks (length >= 16, valid b64 chars)
        # Note: Padding might be omitted or present, we match the charset.
        variants = []
        b64_pattern = r"(?:[A-Za-z0-9+/]{4}){4,}(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?"
        for match in re.finditer(b64_pattern, text):
            block = match.group(0)
            try:
                # Add padding if missing
                padding_needed = len(block) % 4
                if padding_needed:
                    block += "=" * (4 - padding_needed)
                decoded_bytes = base64.b64decode(block, validate=True)
                decoded_str = decoded_bytes.decode('utf-8')
                if cls._is_mostly_readable_utf8(decoded_str):
                    variants.append(decoded_str)
            except Exception:
                pass
        return variants

    @classmethod
    def decode_hex(cls, text: str) -> List[str]:
        """Identifies continuous hex sequences and decodes to ASCII."""
        variants = []
        hex_pattern = r"[0-9a-fA-F]{16,}"
        for match in re.finditer(hex_pattern, text):
            block = match.group(0)
            # Ensure even length
            if len(block) % 2 != 0:
                block = block[:-1]
            try:
                decoded_bytes = bytes.fromhex(block)
                decoded_str = decoded_bytes.decode('utf-8')
                if cls._is_mostly_readable_utf8(decoded_str):
                    variants.append(decoded_str)
            except Exception:
                pass
        return variants

    @classmethod
    def decode_url(cls, text: str) -> Optional[str]:
        """Unquotes URL encoded text if any percentage-encoded strings are present."""
        if "%" in text:
            decoded = urllib.parse.unquote(text)
            if decoded != text:
                return decoded
        return None

    @classmethod
    def decode_rot13(cls, text: str) -> str:
        """Generates ROT13 permutation for heuristic analysis."""
        return codecs.encode(text, 'rot_13')

    @classmethod
    def decode_spacing(cls, text: str) -> Optional[str]:
        """Merges single-spaced or dashed text sequences (e.g., P A S S W O R D, S-E-C-R-E-T)."""
        # Look for sequences of single letters separated by space or hyphen.
        # e.g., P A S S W O R D
        spaced_pattern = r"\b(?:[a-zA-Z0-9][\s\-]){3,}[a-zA-Z0-9]\b"
        variants = []
        
        def replace_spaced(match: re.Match) -> str:
            val = match.group(0)
            # Remove spaces and hyphens
            return re.sub(r"[\s\-]", "", val)
        
        # Replace occurrences in text
        if re.search(spaced_pattern, text):
            return re.sub(spaced_pattern, replace_spaced, text)
            
        return None

    @classmethod
    def decode_all(cls, text: str) -> DeobfuscationReport:
        """
        Runs all decoders against the input text and returns a comprehensive report.
        """
        variants: List[DecodedVariant] = []
        contains_hidden_tokens = False

        # 1. Base64
        b64_results = cls.decode_base64(text)
        for res in b64_results:
            variants.append(DecodedVariant(strategy="Base64", decoded_text=res))
            contains_hidden_tokens = True

        # 2. Hex
        hex_results = cls.decode_hex(text)
        for res in hex_results:
            variants.append(DecodedVariant(strategy="Hex", decoded_text=res))
            contains_hidden_tokens = True

        # 3. URL Decode
        url_result = cls.decode_url(text)
        if url_result:
            variants.append(DecodedVariant(strategy="URL", decoded_text=url_result))

        # 4. Spacing
        spacing_result = cls.decode_spacing(text)
        if spacing_result:
            variants.append(DecodedVariant(strategy="Spacing", decoded_text=spacing_result))
            contains_hidden_tokens = True

        # 5. ROT13 (Always generated for heuristic evaluation)
        rot13_result = cls.decode_rot13(text)
        variants.append(DecodedVariant(strategy="ROT13", decoded_text=rot13_result))

        return DeobfuscationReport(
            original_text=text,
            decoded_variants=variants,
            contains_hidden_tokens=contains_hidden_tokens
        )
